export { default as Main } from './Main'
export { default as Profile } from './Profile/Profile'
export { default as Edit } from './Profile/Edit'
export { default as HowItWorks } from './HowItWorks'
export { default as Help } from './Help'
export { default as Preferences } from './Preferences'
